theme: ["PaperMod"]
title: "Metrics Whisper"

# 首頁的樣式設定開始
params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "Instagram"
      url: "<link>"
    - name: "Linkedin"
      url: "<link2>"
# 首頁的樣式設定結束

# 網站Navbar設定開始
menu:
  main:
    - identifier: Articles
      name: Articles
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# 網站Navbar設定結束