theme: ["PaperMod"]
title: "Metrics Whisper"

# 首頁的樣式設定開始
params:
  homeInfoParams:
    Title: Hi there wave
    Content: 專注於 Google Analytics 的導入與分析。結合 Python 進行數據處理與洞察挖掘，讓分析結果轉化為可執行的優化策略。

  socialIcons: # optional
    - name: "Linkedin"
      url: "<link2>"
    - name: "Email"
      url: "reidchu8350@gmail.com"
# 首頁的樣式設定結束

# 網站Navbar設定開始
menu:
  main:
    - identifier: Articles
      name: Articles
      url: /posts/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# 網站Navbar設定結束